# Mostly generated by deepseek, asking it to convert this
# from zmq to flask

from flask import Flask, request, jsonify
from flask_cors import CORS, cross_origin
import os
from queue import Queue
import signal
import threading
from time import sleep
import traceback

from database import Database
from setup import get_database
from subscribers import BasicSubscriber

import os_query
import search_query
import workspace_query

app = Flask(__name__)
CORS(app)
STATUS_QUEUE = Queue()
PORT = 5000

# # Temporary workaround, set up to prepare for implementation of workspaces
# # Write the directory to read test files from to a text file
# parent_dir = os.path.dirname(os.path.abspath(__file__))
# with open(parent_dir + "/workspace_files/test_dir.txt", "w", encoding="utf-8") as f:
#     f.writelines([parent_dir + "/test_files/"])

# # Read the test file directory from the text file
# with open(parent_dir + "/workspace_files/test_dir.txt", "r", encoding="utf-8") as f:
#     d = f.read()

# # Get the files from the test file directory 
# files = os.listdir(d)
# files = [(f"{d}{x}", True) for x in files]

# DATABASE.add_workspace("ws1", files, "workspace_name", "workspace_description")
# DATABASE.select_workspace("ws1")



# Correct format: {"type":"query_type", "content":{"action":"action_name", "other_content": "value", ...}}
def __has_valid_formatting(message: dict) -> bool:
    has_type = "type" in message.keys()
    has_content = "content" in message.keys()
    has_action = "action" in message["content"].keys()
    return has_type and has_content and has_action


@app.route('/api/data', methods=['POST', 'OPTIONS'])
@cross_origin() 
def handle_data():
    try:
        # Get JSON data from request
        # Handle OPTIONS method called automatically at startup 
        if request.method == 'OPTIONS':
            return '', 200

        message = request.get_json()
        print("Got request JSON")

        if not message:
            print("Got improperly formatted message")
            return jsonify({
                "type": "exception", 
                "content": "No JSON data provided"
            }), 400
        
        print("Got a message: ", message)
        print(type(message))
        
        res = {"type": None, "content": None}
        res_msg = ""
        
        try:
            if not __has_valid_formatting(message):
                raise Exception(f"Invalid message formatting in '{str(message)[:50]}...'")
            
            mtype = message["type"]
            content = message["content"]
            
            if mtype == "os_query":
                res, res_msg = os_query.process(content)
                # res["type"] = "res"
                # res["content"] = res_raw["content"]
                # res_msg = res_raw["msg"]

            elif mtype == "stats_query":
                raise Exception("Not Implemented Yet!")
            elif mtype == "file_history_query":
                raise Exception("Not Implemented Yet!")
            elif mtype == "search_history_query":
                raise Exception("Not Implemented Yet!")
            elif mtype == "workspace_query":
                res, res_msg = workspace_query.process(content, DATABASE)
                # res["content"] = res_raw["content"]
                # res_msg = res_raw["msg"]
                # res["type"] = "res"
            elif mtype == "search_query":
                # results to send back to the front end 
                res, res_msg = search_query.process(content, DATABASE)
                # res = res_raw["content"]
                # print(res)
                # res_msg = res_raw["msg"]

            elif mtype == "settings_query":
                raise Exception("Not Implemented Yet!")
            else:
                raise Exception(f"Invalid query type '{mtype}'")
                
        except Exception as e:
            tb = traceback.print_exc()
            res["type"] = "exception"
            res["content"] = str(e)
            res_msg = f"{str(e)} - {tb}"
        finally:
            if res_msg != "":
                status_socket_sub.update(res_msg)
                terminal_sub.update(res_msg)
            if(not res):
                res = [res_msg]
        
        return jsonify(res)
        
    except Exception as e:
        print("Data threw an exception: ", message, "Error: ", e)
        return jsonify({
            "type": "exception",
            "content": f"Server error: {str(e)}"
        }), 500

@app.route('/api/status', methods=['GET'])
def get_status():
    """Endpoint to get status updates (replaces status_socket)"""
    try:
        # stat_msg = status_socket_sub.get_oldest_update()
        # STATUS_QUEUE.put(stat_msg)
        return jsonify({"status": STATUS_QUEUE.get()})
    except:
        return jsonify({"status": "No updates"})

# Thank you deepseek
class StoppableDaemonThread(threading.Thread):
    """
    Class for handling spawning and killing the state daemon
    """
    def __init__(self):
        super().__init__(daemon=True)
        self._stop_flag = threading.Event()
    
    """
    Tells the daemon to stop what its doing
    """
    def stop(self):
        self._stop_flag.set()
    
    """
    To check if the thread has stopped
    """
    def stopped(self):
        return self._stop_flag.is_set()

"""
For handling when the database should dump, and outputting any messages from the program
"""
class ProgramStateThread(StoppableDaemonThread):
    def run(self):
        while not self.stopped():
            while(terminal_sub.has_update()):
                print(terminal_sub.get_oldest_update())
            if DATABASE.should_dump():
                DATABASE.dump_workspaces()
            try:
                stat_msg = status_socket_sub.get_oldest_update()
                STATUS_QUEUE.put(stat_msg)
            except:
                sleep(3)
            
        print("")


@app.route('/api/kill', methods=['GET'])
def kill():
    
    sleep(1)
    worker.stop()
    worker.join(timeout=2)
    print("You have killed me! WHyYYYy!?")
    os.kill(os.getpid(), signal.SIGINT)
    return jsonify({"success": True, "message": "Server is shutting down..."})


if __name__ == "__main__":

    # Initialize database and subscribers
    DATABASE:Database = get_database()
    print("Initialized database...")
    status_socket_sub = BasicSubscriber()
    stat_sub_id = "status_socket"
    terminal_sub = BasicSubscriber()
    term_sub_id = "term_sub"
    DATABASE.add_subscriber(status_socket_sub, stat_sub_id)
    DATABASE.add_subscriber(terminal_sub, term_sub_id)

    
    print("Starting API main")

    # Start background thread for state management
    worker = ProgramStateThread()
    worker.start()

    print(f"Starting Flask server on http://localhost:{PORT}")
    print("Endpoints:")
    print("  POST /api/data - Main data processing endpoint")
    print("  GET  /api/status - Get status updates")
    print("  GET  /api/kill - Shutdown program")

    app.run(host='0.0.0.0', port=PORT, debug=True, use_reloader=False)