# Mostly generated by deepseek, asking it to convert this
# from zmq to flask

from flask import Flask, request, jsonify
from flask_cors import CORS, cross_origin
import os
from queue import Queue
import signal
import threading
from time import sleep
import traceback

from database import Database
from setup import get_database
from subscribers import BasicSubscriber

from datetime import datetime

import os_query
import search_query
import workspace_query

app = Flask(__name__)
CORS(app)
# STATUS_QUEUE = Queue()
PORT = 5000
STATUS_SOCKET_SUB = BasicSubscriber()
STAT_SUB_ID = "status_socket"
TERMINAL_SUB = BasicSubscriber()
TERM_SUB_ID = "term_sub"


# Correct format: {"type":"query_type", "content":{"action":"action_name", "other_content": "value", ...}}
def __has_valid_formatting(message: dict) -> bool:
    has_type = "type" in message.keys()
    has_content = "content" in message.keys()
    has_action = "action" in message["content"].keys()
    return has_type and has_content and has_action


@app.route('/api/data', methods=['POST', 'OPTIONS'])
@cross_origin() 
def handle_data():
    __notify_subscribers("Data Ping")
    try:
        # Get JSON data from request
        # Handle OPTIONS method called automatically at startup 
        if request.method == 'OPTIONS':
            return '', 200

        message = request.get_json()

        if not message:
            print("Got improperly formatted message")
            return jsonify({
                "type": "exception", 
                "content": "No JSON data provided"
            }), 400
        
        
        res = {"type": None, "content": None}
        res_msg = ""
        
        try:
            if not __has_valid_formatting(message):
                raise Exception(f"Invalid message formatting in '{str(message)[:50]}...'")
            
            mtype = message["type"]
            content = message["content"]
            
            if mtype == "os_query":
                __notify_subscribers(f"OS Query: {str(content)}")
                res, res_msg = os_query.process(content)

            elif mtype == "stats_query":
                raise Exception("Not Implemented Yet!")
            elif mtype == "file_history_query":
                raise Exception("Not Implemented Yet!")
            elif mtype == "search_history_query":
                raise Exception("Not Implemented Yet!")
            elif mtype == "workspace_query":
                __notify_subscribers(f"Workspace Query: {str(content)}")
                res, res_msg = workspace_query.process(content, DATABASE)

            elif mtype == "search_query":
                __notify_subscribers(f"Search Query: {str(content)}")
                # results to send back to the front end 
                res, res_msg = search_query.process(content, DATABASE)

            elif mtype == "settings_query":
                raise Exception("Not Implemented Yet!")
            else:
                raise Exception(f"Invalid query type '{mtype}'")
                
        except Exception as e:
            tb = traceback.print_exc()
            res["type"] = "exception"
            res["content"] = str(e)
            res_msg = f"{str(e)} - {tb}"
        finally:
            if res_msg != "":
                STATUS_SOCKET_SUB.update(res_msg)
                TERMINAL_SUB.update(res_msg)

        
        return jsonify(res)
        
    except Exception as e:
        print("Data threw an exception: ", message, "Error: ", e)
        return jsonify({
            "type": "exception",
            "content": f"Server error: {str(e)}"
        }), 500

@app.route('/api/status', methods=['GET'])
def get_status():
    __notify_subscribers("Status Ping")
    """Endpoint to get status updates (replaces status_socket)"""
    try:
        return jsonify({"status": STATUS_SOCKET_SUB.get_oldest_update()})
    except:
        return jsonify({"status": ""})

# @app.route("/api/busy", methods=["GET"])
# def get_is_busy():
#     __notify_subscribers("Busy Ping")
#     return jsonify({"isbusy": str(DATABASE.get_is_preprocessing())})

# Thank you deepseek
class StoppableDaemonThread(threading.Thread):
    """
    Class for handling spawning and killing the state daemon
    """
    def __init__(self):
        super().__init__(daemon=True)
        self._stop_flag = threading.Event()
    
    """
    Tells the daemon to stop what its doing
    """
    def stop(self):
        self._stop_flag.set()
    
    """
    To check if the thread has stopped
    """
    def stopped(self):
        return self._stop_flag.is_set()

"""
For handling when the database should dump, and outputting any messages from the program
"""
class ProgramStateThread(StoppableDaemonThread):
    def run(self):
        while not self.stopped():
            while(TERMINAL_SUB.has_update()):
                print(TERMINAL_SUB.get_oldest_update())
            if DATABASE.should_dump():
                DATABASE.dump_workspaces()
            # try:
            #     stat_msg = STATUS_SOCKET_SUB.get_oldest_update()
            #     STATUS_QUEUE.put(stat_msg)
            # except:
            sleep(3)
            
        print("")


@app.route('/api/kill', methods=['GET'])
def kill():
    __notify_subscribers("Kill Ping")
    sleep(1)
    worker.stop()
    worker.join(timeout=2)
    DATABASE.close()
    print("You have killed me! WHyYYYy!?")
    os.kill(os.getpid(), signal.SIGINT)
    return jsonify({"success": True, "message": "Server is shutting down..."})


# Lets the front end check if the back end is ready
@app.route('/api/health', methods=['GET'])
def health_check():
    __notify_subscribers("Health Ping")
    if(DATABASE.get_is_preprocessing()):
        return jsonify({"status": "Preprocessing"}), 500
    return jsonify({"status": "ready", "timestamp": datetime.now().isoformat()})


def __notify_subscribers(message:str):
        STATUS_SOCKET_SUB.update(message)
        TERMINAL_SUB.update(message)

if __name__ == "__main__":

    # Initialize database and subscribers
    DATABASE:Database = get_database()
    print("Initialized database...")
    
    DATABASE.add_subscriber(STATUS_SOCKET_SUB, STAT_SUB_ID)
    DATABASE.add_subscriber(TERMINAL_SUB, TERM_SUB_ID)
    DATABASE.purge_backlog_sub()

    
    print("Starting API main")

    # Start background thread for state management
    worker = ProgramStateThread()
    worker.start()

    print(f"Starting Flask server on http://localhost:{PORT}")
    print("Endpoints:")
    print("  POST /api/data - Main data processing endpoint")
    print("  GET  /api/status - Get status updates")
    print("  GET  /api/kill - Shutdown program")

    app.run(host='0.0.0.0', port=PORT, debug=True, use_reloader=False, threaded=False)